# Uncomment the next line to define a global platform for your project


source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target ‘SpotMe’ do
  pod 'Alamofire', '~> 4.0'
  pod ‘Firebase/Core’
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
end

